### ISSUE TITLE
CTRL+F should focus the Find pane

### ISSUE THREAD

**Issue by jordanbtucker** [EXKing-Editor/EXKing-Editor#12]
When I press <kbd>CTRL</kbd>+<kbd>F</kbd>, the Find pane appears, but I have to click into the text box to begin searching for something. It would be a great quality of life feature to have the Find pane focus automatically.

**Comment by ArchLeaders** [comment]
Sadly that control is from a library, and I have very little control over the visual tree of that pane. I am trying to find a way though.

**Comment by ArchLeaders** [comment]
## Proposed Solutions

- Query the Visual Tree and handle `GotFocus/LostFocus`
  - **Issues:** SearchPanel is loaded at an unknown time after view is created
- Suppress the library search panel and build the Sarc search panel into the TextBox
  - **Issues:** May be annoying to manage in multiple editors. _(else: Common view can be managed?)_

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/EXKing-Editor/EXKing-Editor/commit/0ae67b10fd8a0c916ec229d2bfc6346605f93ada
