### ISSUE TITLE
Eta on table editor ?

### ISSUE THREAD

**Issue by alerion921** [EXKing-Editor/EXKing-Editor#14]
Hello, nice software do you have an ETA of the table editor i have made two pretty popular mods for TOTK UIs and need this to progress with removing the X,Y,A,B buttons completly,  thanks for any answers :-)

**Comment by ArchLeaders** [comment]
Since the YAML editor works, this will be less of a priority while I start supporting other formats.

Out of curiosity though, how will an RESTBL table editor help over using the YAML editor?

**Comment by alerion921** [comment]
Im stupid haha nvm, too tired to brain :-)
