### ISSUE TITLE
Unable to add entries to the resource size table

### ISSUE THREAD

**Issue by Icing-weaponry** [EXKing-Editor/EXKing-Editor#17]
HI there,

I'm currently working on an armor upgrade mod for unupgradable armors and I'm at the part where I need to add resources to the table so the games load them but I'm unable to do so.

Anything I add gets turned into a "nul" text when I save it.

Attached is a copy of the table once it's saved with my modifications.
![Capture](https://github.com/EXKing-Editor/EXKing-Editor/assets/65843394/16b3d73d-7ee4-4317-aebb-d067d855aade)

Is there a proper way to do this?

I've tried with it being compressed and uncompressed and both gave me the same result.

Thank you for your time.

**Comment by ArchLeaders** [comment]
I'll look into it. Thanks.

**Comment by ArchLeaders** [comment]
Try again in 0.3.3, I can't seem to recreate the issues anymore.

**Comment by Icing-weaponry** [comment]
as soon as the exe is posted I'll give it a shot and get back to you.
thanks!

**Comment by Icing-weaponry** [comment]
1st test: add value and choose "save as" doesn't work new value isn't added but there's no nul anymore.

2nd test: copy the file and edit it, then choose the option to "save" it. The new value is added and there's no nul symbol.
woooooo upgradable armor here we go!

**Comment by ArchLeaders** [comment]
You sure the first one didn't work? It's the same function, so it should work the same. Did you check the for a hash of the string you added, rather than the string itself?

**Comment by Icing-weaponry** [comment]
at the risk of sounding like an idiot, how can I check the hash of the added line?

**Comment by ArchLeaders** [comment]
You can use a tool like this (https://crc32.online/) to convert your string to a CRC32 hash, then search for the hex value.
