### ISSUE TITLE
0.3.2 vs 0.3.1 Resourcesizetable.zs

### ISSUE THREAD

**Issue by UnlimitedScore** [EXKing-Editor/EXKing-Editor#23]
In the newest update 0.3.2, the app can't seem to open/load resourcesizetable files. I went back to check if the earlier version would work and it did. Not sure what went wrong but thought I'd shine some light on it. 

0.3.2:
![image](https://github.com/EXKing-Editor/EXKing-Editor/assets/120137067/4337a943-855e-4b13-95b1-fac2b94cc5f4)

0.3.1:
![image](https://github.com/EXKing-Editor/EXKing-Editor/assets/120137067/3dd3d3e8-afcf-455e-b30a-f8bf8eb2727d)

**Comment by ArchLeaders** [comment]
Same issue as #21
