### ISSUE TITLE
EX-King-Editor-0.3.3-alpha doesn't open

### ISSUE THREAD

**Issue by WrittenSkate** [EXKing-Editor/EXKing-Editor#24]
When I try to run the app, it just pops up a CMD looking window, the immediately closes. How do you use this? I don't see instructions, and the app doesn't start.

**Comment by ArchLeaders** [comment]
Try opening a command prompt and open the executable from there. If there's an error post it here.

Also do any of the older version work?

**Comment by WrittenSkate** [comment]
Whats the command prompt way to start the app?

Also it does this issue for older version too.

**Comment by ArchLeaders** [comment]
> Whats the command prompt way to start the app?
> 
> Also it does this issue for older version too.

You just open CMD and type the path to the executable. If you're opening a file, type the path to the file after the exe path and it'll open the file.

**Comment by cts23** [comment]
Had the same problem but it just turns out I had to install .NET framework 7.0.5

**Comment by HiroTDK** [comment]
It might be helpful if startup were to verify the .NET installation and provide an error message.

**Comment by ArchLeaders** [comment]
> It might be helpful if startup were to verify the .NET installation and provide an error message.

It can't start at all without the runtime. That's kinda like saying *"drive your car to get it's engine repaired"*, it doesn't really work that way.

My solution is, read documentation (readme)
