### ISSUE TITLE
NX-0.3.5-alpha Issue with converting or editing CtrlGuide_00.msbt file

### ISSUE THREAD

**Issue by Digote** [EXKing-Editor/EXKing-Editor#25]
**Description:**

I have previously tested the msbt_to_yaml.exe tool provided on the Zelda TOTK Modding Hub server for batch conversion, but it fails to convert the CtrlGuide_00.msbt file to .yml format. This specific file seems to be causing the issue as all other conversions work fine.

The problem persists when attempting to editing the CtrlGuide_00.msbt file using NX-Editor as well.

**Logs:**

[2023-06-03-22-12.log](https://github.com/NX-Editor/NX-Editor/files/11644579/2023-06-03-22-12.log)

**Video:**

https://github.com/NX-Editor/NX-Editor/assets/45742711/4195d83b-f6ce-4c89-b9bf-880f75dfb73c

The tool is becoming really good, thank you.

**Comment by ArchLeaders** [comment]
Known issue in https://github.com/EPD-Libraries/msbt/issues/1
