### ISSUE TITLE
Editing TotK's Bootup.Nin_NX_NVN.pack.zs results in strange game behavior.

### ISSUE THREAD

**Issue by Serfrost** [EXKing-Editor/EXKing-Editor#31]
I'm not sure if this is due to a mishandling of the decompression or compression process, but for awhile now we have been encountering problems where editing this file will result in Grass failing to spawn, in addition to New Locations failing to register or show up on the in-game map. I'm not technical enough to know what the cause could be.

For reference, I edit Bootup.Nin_NX_NVN.pack.zs to remove Interior Fog. You can grab one of my edits here:

- 1.0.0 : https://files.gamebanana.com/mods/v100_serfrosts_indoor_defogger.zip
- 1.1.0 + 1.1.1 : https://files.gamebanana.com/mods/v110_111_serfrosts_indoor_defogger.zip
- 1.2.0 : https://files.gamebanana.com/mods/v112_serfrosts_indoor_defogger.zip

`Bootup.Nin_NX_NVN.pack.zs`
`→ WorldMgr`
`→ PrequelIndoorPalette`

The mod simply alters the FogStart and FogEnd variables. There were similar reports for other edits that were not related to fog, such as setting the game's Resolution by altering the following file:

`Bootup.Nin_NX_NVN.pack.zs`
`→ System`
`→ GameGraphics`
`→ ModelSceneExtensionParam`
`→ Default.game__gfx__ModelSceneExtensionParam.bgyml`

As these mods are unrelated in the files they edit, aside from the host file, the only other cause I can think of is NX-Editor itself. If this could be looked into / fixed, I'm sure it would be worth it.

User confirmation: https://www.reddit.com/r/NewYuzuPiracy/comments/143nzbm/comment/jncfq9c/?utm_source=share&utm_medium=web2x&context=3

**Comment by ArchLeaders** [comment]
Do these issue occur when simply re-serializing any one of these files (without edits)?

**Comment by Serfrost** [comment]
> Do these issue occur when simply re-serializing any one of these files (without edits)?

This I cannot test for now, but I'll try to look into it when I get time.

**Comment by ArchLeaders** [comment]
Sounds good, I'll leave this issue open for now.

**Comment by Serfrost** [comment]
For anyone who searches for a similar issue, things to note:

- Try dumping romfs with Ryujinx instead of Yuzu.
- Try a fresh game dump to make sure it's not corruption.
- Try exporting the files before editing them, then replacing them afterwards.
- Lastly, try using ZSTD separately with default compression.

One of these things managed to resolve the issue, not sure which.

**Comment by Cloud01-pixel** [comment]
Lastly, try using ZSTD separately with default compression. - You need a 7zip version on github for this. - Extracts the main model file, then find the texture. As stated, the mods are I think, an archive though compressed. So the other question would be why extract the main boot file? Though that is smart to include it within an archive. :) What one did was probably edited too many mods at once, or executed them within the file. Now if I can only recompress to compatible format or knew the file tree. I believe NX editor might be doing what it is supposed to do. But I don't really know.
