### ISSUE TITLE
Opening any file results in "binding" errors

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [EXKing-Editor/EXKing-Editor#33]
> 09:38:12:795 [TryLoadEditor] | "../../EXKing-Editor/src/ExKingEditor/Models/EditorMgr.cs":29 | Processing Player.pack.zs
> [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #28395444)
> [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #54232412)
> [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #18329666)
> [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #30749271)
> [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #8307988)
> [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #7663035)
> [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #1858451)
> [Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #16706408)
> [Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #11041789)
> [Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #63509856)
> [Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #34717793)

No matter what I do opening any file spits out these errors.

I'm using the latest version.

**Comment by ArchLeaders** [comment]
Just an issue with `Avalonia.Behaviours` binding before the data context is applied, it's not a real error.
