### ISSUE TITLE
Zelda TOTK Japanese msbt file, ruby does not display correctly when using Kanji characters.

### ISSUE THREAD

**Issue by zaranrapu** [EXKing-Editor/EXKing-Editor#36]
Hiragana is written in the Data field, but it cannot be displayed correctly.

SpObj_FlameThrower_A_01_Adjective: |
  <0 Type='0' Data='040008004b308a3085304630'/>火龍の<0 Type='0' Data='0200060042305f307e30'/>頭

This is how it should be.

SpObj_FlameThrower_A_01_Adjective: |
  <0 Type='0' Data='かりゅう'/>火龍の<0 Type='0' Data='あたま'/>頭
![msbt](https://github.com/NX-Editor/NX-Editor/assets/11900318/66b958a0-4028-4f3c-9701-48c10816dde2)

**Comment by ArchLeaders** [comment]
The data field is binary data, not decoded strings. This is just an unknown tag implementation, if you have spec details you can report an issue on the msbt repository for **Group `0`, Type `0`**.

https://github.com/EPD-Libraries/msbt/issues
