### ISSUE TITLE
Can't import an exported map file

### ISSUE THREAD

**Issue by AsteroidPizza39** [EXKing-Editor/EXKing-Editor#38]
I imported /Banc/Mainfield/E-6_Static.bcett.byml.zs, made some edits, then exported it. Upon trying to import it again, I get a Dictionary Mismatch. 

[2023-06-12-18-22.log](https://github.com/NX-Editor/NX-Editor/files/11728849/2023-06-12-18-22.log)

**Comment by ArchLeaders** [comment]
This was fixed previously, are you using the latest version?

**Comment by AsteroidPizza39** [comment]
i’m so sorry that’s on me. I’ve been using 0.3.1 because 0.3.6 has some issues when editing RSTB (it doesn’t appear)
