### ISSUE TITLE
Not loading msbt files, crashing when attempting

### ISSUE THREAD

**Issue by ghost** [EXKing-Editor/EXKing-Editor#39]
First, many thanks for your work. I am having a lot of fun with it :).

In 3.7, I get this error when trying to open a msbt file:

`13:32:59:104 [TryLoadEditor] | "../../../../../../../../runner/work/NX-Editor/NX-Editor/src/NxEditor/Component/EditorMgr.cs":30 | Processing Boss.msbt
terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::to_bytes
Aborted (core dumped)
`

I'm running ubuntu, and I believe I have the dependencies installed. Would there be anything I'm missing?

**Comment by ArchLeaders** [comment]
Hm, probably an issue with the native library assuming a different default encoding on linux. Not really sure though.

I don't get it on Windows, but I'll see if I can replicate this on my linux machine.

**Comment by ArchLeaders** [comment]
Seems to be an issue with https://github.com/EPD-Libraries/msbt, you can track the issue there.

https://github.com/EPD-Libraries/msbt/issues/2

**Comment by ghost** [comment]
Thank you!
