### ISSUE TITLE
Error in binding to `Avalonia.Input.Keybinding` when trying to load a RSTB

### ISSUE THREAD

**Issue by Reso-Nin** [EXKing-Editor/EXKing-Editor#41]
Hi, I am trying to merge some RSTBs from a couple mods for TOTK and I got the latest version of NX-Editor and installed NET7 64x runtime as required. Dumped the RomFS and pointed the program to it successfully. I can load GameActorInfo112 and others, but not ResourceSizeTable112 which is the main one I need. The log is below. 

Win10 x64, NX-Editor V0.3.7alpha, Net7 x64
[2023-06-20-00-10.log](https://github.com/NX-Editor/NxEditor/files/11793889/2023-06-20-00-10.log)

**Comment by Reso-Nin** [comment]
Okay I found the Hashtable and I think that has solved my issue.

**Comment by verbes4** [comment]
getting this same issue, where can i get the hash table lol

edit: nevermind i just searched in the totk modding hub server lol, my bad

edit 2: nevermind, still getting `[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #28263486)`

**Comment by ArchLeaders** [comment]
> getting this same issue, where can i get the hash table lol
> 
> edit: nevermind i just searched in the totk modding hub server lol, my bad
> 
> edit 2: nevermind, still getting `[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #28263486)`

That's not an error with any of my code, just an issue with Avalonia

**Comment by verbes4** [comment]
ohh my bad lol i should have read the entire issue first, thanks :)
