### ISSUE TITLE
Game Crashes when using edited Tag.Product.<game_ver>.rstbl.byml.zs

### ISSUE THREAD

**Issue by AsteroidPizza39** [EXKing-Editor/EXKing-Editor#46]
exactly what it says in the title

**Comment by ArchLeaders** [comment]
This is from oead - I think it's an issue with binary tags

**Comment by AsteroidPizza39** [comment]
New discussions believe it’s because it’s BYML v7, which doesn’t have write support  i’d suggest reading through general in the totk modding hub, it got talked about for a bit there are the reason standalone armors don’t work

**Comment by ArchLeaders** [comment]
Byml v7 specific files won't open at all, and the same issue is found in a BE v4 file as well.
