### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by bastuijnman** [EXKing-Editor/EXKing-Editor#49]
I've been dipping my feet into TOTK modding by emulating my game dump on my Macbook Pro (bold I know). The tooling seems to mostly geared towards windows/linux, but I've been able to make NxEditor work on my machine.

Would there be any interest in supporting this moving forward? Asking it in advance because it will require changes to the underlying libraries, which either need to be done in the respective submodules (as separate PR's) or (the dirty way) as a patch file that's applied before building for MacOS.

There's still some kinks to work out in terms of random crashes, for example when double clicking or closing tabs but if there's a use for it other than me just playing around more than happy to contribute these changes back (in which case I'll have to do them properly).

**Comment by ArchLeaders** [comment]
> I've been dipping my feet into TOTK modding by emulating my game dump on my Macbook Pro (bold I know). The tooling seems to mostly geared towards windows/linux, but I've been able to make NxEditor work on my machine.
> 
> Would there be any interest in supporting this moving forward? Asking it in advance because it will require changes to the underlying libraries, which either need to be done in the respective submodules (as separate PR's) or (the dirty way) as a patch file that's applied before building for MacOS.
> 
> There's still some kinks to work out in terms of random crashes, for example when double clicking or closing tabs but if there's a use for it other than me just playing around more than happy to contribute these changes back (in which case I'll have to do them properly).

My only issue with this is I can't ever fully support macos, cause I don't have a mac to test on (and the VM's are too slow to do anything on). But if your up for getting the libraries built for macos (which should already work on most of them) I'm down to have macos builds up, and just explicitly mention that macos isn't supported.

**Comment by ArchLeaders** [comment]
Might also be good to make any changes on [NxEditor@plugin-base](https://github.com/NX-Editor/NxEditor/tree/plugin-base), or just wait for the 1.0.0 changes to be merged. So much stuff has changed now that it'd be kind of annoying to merge anything downstream.

**Comment by bastuijnman** [comment]
Aight I'll at least wait for the 1.0.0 changes to drop to the main branch then.

I 100% get that maintaining platforms that you don't own is a heck of a job and especially if not a ton of people are using it (I imagine). More than happy to help out maintaining it if needed, but that's kinda why I made the issue as well to see if there are other people interested in support for Mac. 

In any case, with the support I also updated the Avalonia dependencies to 11.0.0 so might be able to contribute that at least (though the Settings page needs updating)

Edit: nevermind I see that you already did the upgrade on that branch 😅

**Comment by ArchLeaders** [comment]
Merged everything into master now, so feel free to make a PR if you want. Most of the native libs have moved to [NX-Editor/NxEditor.EpdPlugin](https://github.com/NX-Editor/NxEditor.EpdPlugin) now though, so you may want to make a PR there too (once I re-implement the editors of course)

**Comment by bastuijnman** [comment]
👍 will take a look later today

**Comment by ArchLeaders** [comment]
Should probably leave this open until macos support itself is resolved, we can close this when the PR is merged

**Comment by bastuijnman** [comment]
Aight 👌

**Comment by nicolefallen** [comment]
Hate leaving a comment just to say there is interest in support for Mac but...there is. I did not manage to get as far as you, @bastuijnman, and would be extremely grateful for even a buggy Mac port.

**Comment by bastuijnman** [comment]
@nicolefallen the pre-`1.0.0` structure required quite a few modifications to the build setups of the native libraries that are in use. However since @ArchLeaders made quite some modifications to the structure for `1.0.0` I've not made any attempts to create PR's for those.

The new version runs fine on MacOS so far, but that does not include any of the plugins yet (been digging into the plugin repos but I've not seen anything that would make it hard to run on MacOs).

Will let you know more once I figure out how to run the plugins 😄

**Comment by ArchLeaders** [comment]
MacOS builds seems mostly functional now. Gonna close this issue for now, we can open it again if any major issues pop up.
