### ISSUE TITLE
Installation Issues on Linux

### ISSUE THREAD

**Issue by mlc2020** [EXKing-Editor/EXKing-Editor#60]
`NxEditor.Launcher` installation targets `/usr/share/applications` which is locked behind root on Linux. Trying to get the applicable permissions to allow the launcher to install there is not ideal due to having to run the program as root. Additionally, on Steam Deck this involves disabling SteamOS's readonly filesystem. Finally, due to being as root, `NxEditor.Launcher` has trouble locating the installed dotnet runtime.

Admittedly, I'm not too familiar with Linux so if there's an easy fix I'm not seeing please let me know. Otherwise, would it be possible to install the editor to `/home/%USER%/Desktop` or `/home/%USER%/Applications` or somewhere similarly less invasive?

**Comment by ArchLeaders** [comment]
It only installs the desktop shortcuts there you should be able to install without root permissions if you uncheck the "Create Desktop Shortcuts" option in the installer.

**Comment by mlc2020** [comment]
Perfect, don't know how I overlooked that. Thanks!
