### ISSUE TITLE
MSBT Tag 201 saving issue reminder for Arch

### ISSUE THREAD

**Issue by Waikuteru** [EXKing-Editor/EXKing-Editor#61]
You know what it's about (hopefully :D)

**Comment by ArchLeaders** [comment]
> I would like to remind that if you add this in NX, you can't save but when using msbt-to-yml.exe it works:
> ![image](https://github.com/NX-Editor/NxEditor/assets/80713508/2a786b25-d78a-4e5d-a9f0-ea74567c920d)

**Comment by ArchLeaders** [comment]
User error.
