### ISSUE TITLE
Static LargeDungeonThunder file not saveable

### ISSUE THREAD

**Issue by Waikuteru** [EXKing-Editor/EXKing-Editor#62]
With the latest NX Editor v1.4.0, I cannot save this vanilla file **LargeDungeonThunder_Static.bcett.byml.zs** (the _Dynamic version works). The error output is `"The output byte buffer is too small to contain the encoded data, encoding codepage '65001' and fallback 'System.Text.EncoderReplacementFallback'. (Parameter 'bytes')"`

[LargeDungeonThunder.zip](https://github.com/NX-Editor/NxEditor/files/15031839/LargeDungeonThunder.zip)

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/EPD-Libraries/BymlLibrary/commit/54cbf2c0c2399cf90eede89cd0ab9fcf80b232dd
