### ISSUE TITLE
Editing player.pack.zs for TOTK gives error "ZstdException: Dictionary mismatch"

### ISSUE THREAD

**Issue by DunhamGitHub** [EXKing-Editor/EXKing-Editor#66]
- Windows 64bit version
- Installed with TOTK customization

<img width="844" alt="Screenshot 2024-05-12 at 06 53 36" src="https://github.com/NX-Editor/NxEditor/assets/6884752/fc3af93c-ee49-4f1a-b473-140c6b38b5e1">

**Comment by ArchLeaders** [comment]
Did you configure your game path?

**Comment by DunhamGitHub** [comment]
> Did you configure your game path?

Yes, sir. (switch dump from Yuzu, works with BCML so ...)

<img width="845" alt="Screenshot 2024-05-12 at 07 27 09" src="https://github.com/NX-Editor/NxEditor/assets/6884752/066d51c0-7980-40d1-8c55-ce3a828d6d13">

**Comment by LordBubblesDev** [comment]
The title ID in your game path is the one for Breath of the Wild, not Tears of the Kingdom

**Comment by DunhamGitHub** [comment]
> The title ID in your game path is the one for Breath of the Wild, not Tears of the Kingdom

Damn. You are right. Thanks for your time.
