### ISSUE TITLE
Editing player.pack.zs for TOTK gives error "NotSupportedException: The provided lFileHandle..."

### ISSUE THREAD

**Issue by DunhamGitHub** [EXKing-Editor/EXKing-Editor#67]
- Dumped TOTK 1.2.1 with Yuzu
- Pointed NxEditor to _correct_ romf folder

[Player.pack.zs.zip](https://github.com/NX-Editor/NxEditor/files/15286146/Player.pack.zs.zip)

<img width="946" alt="Screenshot 2024-05-12 at 14 02 41" src="https://github.com/NX-Editor/NxEditor/assets/6884752/2b5717ac-0c38-4656-8049-f3f087501193">

<img width="797" alt="Screenshot 2024-05-12 at 14 02 31" src="https://github.com/NX-Editor/NxEditor/assets/6884752/826d93aa-f827-4e6f-a964-e7462bfd2d1c">

**Comment by LordBubblesDev** [comment]
- Did you click the "Save" button in the settings after setting the path?
- Did you install both the TotK and EPD plugins through the launcher? (it's on [the release](https://github.com/NX-Editor/NxEditor/releases/tag/1.4.0))
- When you open NX Editor, does it show in the command line that the TotK and EPD plugins are loaded? (View > Show/Hide Console)

**Comment by DunhamGitHub** [comment]
> * Did you click the "Save" button in the settings after setting the path?
> * Did you install both the TotK and EPD plugins through the launcher? (it's on [the release](https://github.com/NX-Editor/NxEditor/releases/tag/1.4.0))
> * When you open NX Editor, does it show in the command line that the TotK and EPD plugins are loaded? (View > Show/Hide Console)

Thank you. Following was unticked...

<img width="605" alt="Screenshot 2024-05-12 at 16 46 58" src="https://github.com/NX-Editor/NxEditor/assets/6884752/857b76bb-87ef-423a-b055-fd9a94648fab">
