### ISSUE TITLE
How do I import a Hash Table?

### ISSUE THREAD

**Issue by LaykaKiro** [EXKing-Editor/EXKing-Editor#73]
I'm trying to edit my RSTB file and can't because it needs a hash table which is never explained why...

**Comment by ArchLeaders** [comment]
Can you send the full error?

**Comment by LaykaKiro** [comment]
There's no error. I just don't have a hash table.

**Comment by LaykaKiro** [comment]
I tried the hash tool you made but you didn't explain at all how to structure the path so I literally couldn't get it to work.

**Comment by ArchLeaders** [comment]
If you are referring to the [string table](https://github.com/NX-Editor/NxEditor.EpdPlugin/blob/master/src/Resources/RestblEditor.Info.md#string-table), it is only a convenience feature, not a requirement.

You can use the editor without this if you know the resource keys.

> I tried the hash tool you made but you didn't explain at all how to structure the path so I literally couldn't get it to work.

Are you referring to [ModuleSystem.HashCalculator](https://github.com/ArchLeaders/ModuleSystem.HashCalculator)?

If you are, that script is only for ModuleSystem games like TotK, it is unlikely to work on other games. You will most likely need to create your own script to locate the file names for whatever game you're modding.

**Comment by LaykaKiro** [comment]
I'm referring to the TotK Hash Calculator. It was under your name last I checked. And unfortunately I have no clue what resource keys are either. I'm super new to modding and haven't found a single tutorial that doesn't assume I know everything, which I don't... I know next to nothing...

**Comment by LaykaKiro** [comment]
My honest mistake it's by TotKMods but you were present above the little section that shows the files.

**Comment by ArchLeaders** [comment]
If you are modding TotK, manually editing the RESTBL is obsolete, you can use [RstbCalculator](https://github.com/ArchLeaders/TotK-RstbCalculator) or [restbl](https://github.com/MasterBubbles/restbl) to automatically generate it.

If you are just playing with mods, you can use [TKMM](https://tkmm.org) to merge mods automatically.

If you need further help you can join the [TKMM](https://discord.gg/BbVXenRFVc), or [TotK modding](https://discord.gg/nEFVf8A) Discord server.

I hope that helps, and sorry for the confusion; modding is not very easy to get into at the moment.

**Comment by LaykaKiro** [comment]
I did want to edit the RESTBL and after a quick read through the two tools. I may need a really extreme hand-holding to even start. I can't deal with text-based instructions as a whole...

**Comment by LaykaKiro** [comment]
I'll try the modding Discord eventually.

**Comment by ArchLeaders** [comment]
> I did want to edit the RESTBL and after a quick read through the two tools. I may need a really extreme hand-holding to even start. I can't deal with text-based instructions as a whole...

For [restbl](https://github.com/MasterBubbles/restbl) you can mostly ignore the readme, if you download the lite version it's a very simple interface to use.

![image](https://github.com/user-attachments/assets/3d90db66-ec04-4491-9f2a-046de1e3f6c1)

Browse for your mod folder (romfs) in the top mod folder (single mod) then press Calculate RESTBL.

That's all you need to do.

**Comment by LaykaKiro** [comment]
It replaced the original file *in* the mod folder with another one and that's it... I have to be some sort of actual fucking moron...

**Comment by ArchLeaders** [comment]
> It replaced the original file _in_ the mod folder with another one and that's it... I have to be some sort of actual fucking moron...

That is all it's supposed to do, it's just editing that one file (`System/Resource/ResourceSizeTable.Product.121.rsizetable.zs`)

**Comment by LaykaKiro** [comment]
But, how the Hell do *I* edit that file!?

**Comment by LaykaKiro** [comment]
Like, I truly don't understand what these tools are even meant to do at this point!!! I feel like I'm losing my damned mind!!!

**Comment by ArchLeaders** [comment]
> Like, I truly don't understand what these tools are even meant to do at this point!!! I feel like I'm losing my damned mind!!!

You don't need to edit the RESTBL file, it's just a list of every file's allocation size, that's why it can be autogenerated.

**Comment by LaykaKiro** [comment]
But... What the Hell do I edit if I want to add/remove/modify weapons/armor?

**Comment by LaykaKiro** [comment]
I'm sorry for my attitude by the by. I don't have an excuse for my little breakdown...

**Comment by ArchLeaders** [comment]
> But... What the Hell do I edit if I want to add/remove/modify weapons/armor?

For editing models, you'll want to look into the `Models` folder
For actors (weapons, enemies, armour, pretty much any in-game object) you'll want to look into `Pack/Actor`

There are many other things you can edit of course, but that's the more basic stuff (which is not very basic, but nothing in this game is that basic).

The file types you will edit are mostly `.pack` (Archive format, like zip), `.byml/.bgyml` (Text based parameters, like a yaml or json file) and `.bfres/.txtg` (Models, animations and textures)

.pack and .byml (and .bgyml, same format as .byml) can be edited with NX-Editor, but for bfres and txtg you'll need [switch toolbox](https://github.com/KillzXGaming/Switch-Toolbox).

You can find some tutorials on GameBanana: https://gamebanana.com/tuts/games/7617

And no worries about the attitude. This game is not easy to mod; just make sure you go easy on yourself when starting.

**Comment by LaykaKiro** [comment]
Thank you so very very much for explaining stuff and causing me to question myself. I'm super duper sorry again for my attitude! I actually managed to achieve what I needed! Thank you again! I'm sorry again for how kind of panicked I seemed!

**Comment by ArchLeaders** [comment]
> Thank you so very very much for explaining stuff and causing me to question myself. I'm super duper sorry again for my attitude! I actually managed to achieve what I needed! Thank you again! I'm sorry again for how kind of panicked I seemed!

No worries, glad you found what you needed. Feel free to [email me](mailto:archleaders@outlook.com) if you have any questions.
